[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Optional: specify upload port manually (COMx) if auto-detection fails
; upload_port = COM4

lib_deps =
    knolleary/PubSubClient@^2.8
